// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'core/models/objectbox_entities.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 8632908835836996955),
    name: 'ArtistScoreEntity',
    lastPropertyId: const obx_int.IdUid(4, 6081268516144066571),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8075099286635864020),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1364604299991801962),
        name: 'artist',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 108281488429462901),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5587424284888047123),
        name: 'score',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6081268516144066571),
        name: 'listeningTimeSeconds',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 3314733562263411748),
    name: 'LikedSongEntity',
    lastPropertyId: const obx_int.IdUid(2, 528618893913277280),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1260222917979696202),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 528618893913277280),
        name: 'songId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(2, 189957034368685619),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 3162607642279285744),
    name: 'PlayCountEntity',
    lastPropertyId: const obx_int.IdUid(3, 127138895229558762),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3575194204395196104),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7426645639815148079),
        name: 'songId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(3, 1390977040743255012),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 127138895229558762),
        name: 'count',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 215814196929102299),
    name: 'PlaylistEntity',
    lastPropertyId: const obx_int.IdUid(3, 1474523494619023276),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1230337618724078588),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 673691709699598858),
        name: 'name',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(4, 7355379647484401323),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1474523494619023276),
        name: 'imagePath',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(1, 8704535822728462939),
        name: 'songs',
        targetId: const obx_int.IdUid(6, 1311467324580566175),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 3291702195195788920),
    name: 'SearchHistoryEntity',
    lastPropertyId: const obx_int.IdUid(3, 2865170068010330566),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1357237277273605675),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 208415122124100690),
        name: 'query',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2865170068010330566),
        name: 'timestamp',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 1311467324580566175),
    name: 'SongEntity',
    lastPropertyId: const obx_int.IdUid(9, 6293221523930204558),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2704676496189655761),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8581885044575556394),
        name: 'songId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(5, 80378336110315379),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5450353782807221623),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3966702646048308422),
        name: 'artist',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5635055790770288773),
        name: 'album',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2449868467259353053),
        name: 'artUri',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6290243596636626650),
        name: 'durationSeconds',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 6348157095181649026),
        name: 'hasFlac',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 6293221523930204558),
        name: 'hasHiRes',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(6, 1311467324580566175),
    lastIndexId: const obx_int.IdUid(5, 80378336110315379),
    lastRelationId: const obx_int.IdUid(1, 8704535822728462939),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    ArtistScoreEntity: obx_int.EntityDefinition<ArtistScoreEntity>(
      model: _entities[0],
      toOneRelations: (ArtistScoreEntity object) => [],
      toManyRelations: (ArtistScoreEntity object) => {},
      getId: (ArtistScoreEntity object) => object.id,
      setId: (ArtistScoreEntity object, int id) {
        object.id = id;
      },
      objectToFB: (ArtistScoreEntity object, fb.Builder fbb) {
        final artistOffset = fbb.writeString(object.artist);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, artistOffset);
        fbb.addInt64(2, object.score);
        fbb.addInt64(3, object.listeningTimeSeconds);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final artistParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final scoreParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final listeningTimeSecondsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final object = ArtistScoreEntity(
          artist: artistParam,
          score: scoreParam,
          listeningTimeSeconds: listeningTimeSecondsParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    LikedSongEntity: obx_int.EntityDefinition<LikedSongEntity>(
      model: _entities[1],
      toOneRelations: (LikedSongEntity object) => [],
      toManyRelations: (LikedSongEntity object) => {},
      getId: (LikedSongEntity object) => object.id,
      setId: (LikedSongEntity object, int id) {
        object.id = id;
      },
      objectToFB: (LikedSongEntity object, fb.Builder fbb) {
        final songIdOffset = fbb.writeString(object.songId);
        fbb.startTable(3);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, songIdOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final songIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final object = LikedSongEntity(songId: songIdParam)
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    PlayCountEntity: obx_int.EntityDefinition<PlayCountEntity>(
      model: _entities[2],
      toOneRelations: (PlayCountEntity object) => [],
      toManyRelations: (PlayCountEntity object) => {},
      getId: (PlayCountEntity object) => object.id,
      setId: (PlayCountEntity object, int id) {
        object.id = id;
      },
      objectToFB: (PlayCountEntity object, fb.Builder fbb) {
        final songIdOffset = fbb.writeString(object.songId);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, songIdOffset);
        fbb.addInt64(2, object.count);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final songIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final countParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final object = PlayCountEntity(songId: songIdParam, count: countParam)
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    PlaylistEntity: obx_int.EntityDefinition<PlaylistEntity>(
      model: _entities[3],
      toOneRelations: (PlaylistEntity object) => [],
      toManyRelations: (PlaylistEntity object) => {
        obx_int.RelInfo<PlaylistEntity>.toMany(1, object.id): object.songs,
      },
      getId: (PlaylistEntity object) => object.id,
      setId: (PlaylistEntity object, int id) {
        object.id = id;
      },
      objectToFB: (PlaylistEntity object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final imagePathOffset = object.imagePath == null
            ? null
            : fbb.writeString(object.imagePath!);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, imagePathOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final imagePathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final object = PlaylistEntity(
          name: nameParam,
          imagePath: imagePathParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        obx_int.InternalToManyAccess.setRelInfo<PlaylistEntity>(
          object.songs,
          store,
          obx_int.RelInfo<PlaylistEntity>.toMany(1, object.id),
        );
        return object;
      },
    ),
    SearchHistoryEntity: obx_int.EntityDefinition<SearchHistoryEntity>(
      model: _entities[4],
      toOneRelations: (SearchHistoryEntity object) => [],
      toManyRelations: (SearchHistoryEntity object) => {},
      getId: (SearchHistoryEntity object) => object.id,
      setId: (SearchHistoryEntity object, int id) {
        object.id = id;
      },
      objectToFB: (SearchHistoryEntity object, fb.Builder fbb) {
        final queryOffset = fbb.writeString(object.query);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, queryOffset);
        fbb.addInt64(2, object.timestamp);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final queryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final timestampParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final object = SearchHistoryEntity(
          query: queryParam,
          timestamp: timestampParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    SongEntity: obx_int.EntityDefinition<SongEntity>(
      model: _entities[5],
      toOneRelations: (SongEntity object) => [],
      toManyRelations: (SongEntity object) => {},
      getId: (SongEntity object) => object.id,
      setId: (SongEntity object, int id) {
        object.id = id;
      },
      objectToFB: (SongEntity object, fb.Builder fbb) {
        final songIdOffset = fbb.writeString(object.songId);
        final titleOffset = fbb.writeString(object.title);
        final artistOffset = fbb.writeString(object.artist);
        final albumOffset = fbb.writeString(object.album);
        final artUriOffset = object.artUri == null
            ? null
            : fbb.writeString(object.artUri!);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, songIdOffset);
        fbb.addOffset(2, titleOffset);
        fbb.addOffset(3, artistOffset);
        fbb.addOffset(4, albumOffset);
        fbb.addOffset(5, artUriOffset);
        fbb.addInt64(6, object.durationSeconds);
        fbb.addBool(7, object.hasFlac);
        fbb.addBool(8, object.hasHiRes);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final songIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final artistParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final albumParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final artUriParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final durationSecondsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final hasFlacParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          18,
          false,
        );
        final hasHiResParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          20,
          false,
        );
        final object = SongEntity(
          songId: songIdParam,
          title: titleParam,
          artist: artistParam,
          album: albumParam,
          artUri: artUriParam,
          durationSeconds: durationSecondsParam,
          hasFlac: hasFlacParam,
          hasHiRes: hasHiResParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ArtistScoreEntity] entity fields to define ObjectBox queries.
class ArtistScoreEntity_ {
  /// See [ArtistScoreEntity.id].
  static final id = obx.QueryIntegerProperty<ArtistScoreEntity>(
    _entities[0].properties[0],
  );

  /// See [ArtistScoreEntity.artist].
  static final artist = obx.QueryStringProperty<ArtistScoreEntity>(
    _entities[0].properties[1],
  );

  /// See [ArtistScoreEntity.score].
  static final score = obx.QueryIntegerProperty<ArtistScoreEntity>(
    _entities[0].properties[2],
  );

  /// See [ArtistScoreEntity.listeningTimeSeconds].
  static final listeningTimeSeconds =
      obx.QueryIntegerProperty<ArtistScoreEntity>(_entities[0].properties[3]);
}

/// [LikedSongEntity] entity fields to define ObjectBox queries.
class LikedSongEntity_ {
  /// See [LikedSongEntity.id].
  static final id = obx.QueryIntegerProperty<LikedSongEntity>(
    _entities[1].properties[0],
  );

  /// See [LikedSongEntity.songId].
  static final songId = obx.QueryStringProperty<LikedSongEntity>(
    _entities[1].properties[1],
  );
}

/// [PlayCountEntity] entity fields to define ObjectBox queries.
class PlayCountEntity_ {
  /// See [PlayCountEntity.id].
  static final id = obx.QueryIntegerProperty<PlayCountEntity>(
    _entities[2].properties[0],
  );

  /// See [PlayCountEntity.songId].
  static final songId = obx.QueryStringProperty<PlayCountEntity>(
    _entities[2].properties[1],
  );

  /// See [PlayCountEntity.count].
  static final count = obx.QueryIntegerProperty<PlayCountEntity>(
    _entities[2].properties[2],
  );
}

/// [PlaylistEntity] entity fields to define ObjectBox queries.
class PlaylistEntity_ {
  /// See [PlaylistEntity.id].
  static final id = obx.QueryIntegerProperty<PlaylistEntity>(
    _entities[3].properties[0],
  );

  /// See [PlaylistEntity.name].
  static final name = obx.QueryStringProperty<PlaylistEntity>(
    _entities[3].properties[1],
  );

  /// See [PlaylistEntity.imagePath].
  static final imagePath = obx.QueryStringProperty<PlaylistEntity>(
    _entities[3].properties[2],
  );

  /// see [PlaylistEntity.songs]
  static final songs = obx.QueryRelationToMany<PlaylistEntity, SongEntity>(
    _entities[3].relations[0],
  );
}

/// [SearchHistoryEntity] entity fields to define ObjectBox queries.
class SearchHistoryEntity_ {
  /// See [SearchHistoryEntity.id].
  static final id = obx.QueryIntegerProperty<SearchHistoryEntity>(
    _entities[4].properties[0],
  );

  /// See [SearchHistoryEntity.query].
  static final query = obx.QueryStringProperty<SearchHistoryEntity>(
    _entities[4].properties[1],
  );

  /// See [SearchHistoryEntity.timestamp].
  static final timestamp = obx.QueryIntegerProperty<SearchHistoryEntity>(
    _entities[4].properties[2],
  );
}

/// [SongEntity] entity fields to define ObjectBox queries.
class SongEntity_ {
  /// See [SongEntity.id].
  static final id = obx.QueryIntegerProperty<SongEntity>(
    _entities[5].properties[0],
  );

  /// See [SongEntity.songId].
  static final songId = obx.QueryStringProperty<SongEntity>(
    _entities[5].properties[1],
  );

  /// See [SongEntity.title].
  static final title = obx.QueryStringProperty<SongEntity>(
    _entities[5].properties[2],
  );

  /// See [SongEntity.artist].
  static final artist = obx.QueryStringProperty<SongEntity>(
    _entities[5].properties[3],
  );

  /// See [SongEntity.album].
  static final album = obx.QueryStringProperty<SongEntity>(
    _entities[5].properties[4],
  );

  /// See [SongEntity.artUri].
  static final artUri = obx.QueryStringProperty<SongEntity>(
    _entities[5].properties[5],
  );

  /// See [SongEntity.durationSeconds].
  static final durationSeconds = obx.QueryIntegerProperty<SongEntity>(
    _entities[5].properties[6],
  );

  /// See [SongEntity.hasFlac].
  static final hasFlac = obx.QueryBooleanProperty<SongEntity>(
    _entities[5].properties[7],
  );

  /// See [SongEntity.hasHiRes].
  static final hasHiRes = obx.QueryBooleanProperty<SongEntity>(
    _entities[5].properties[8],
  );
}
